
run:
	g++ -S -O2 -fno-asynchronous-unwind-tables -fno-unwind-tables -fno-exceptions -fno-rtti -fno-stack-protector -fcf-protection=none -fno-ident -no-pie -fno-pic main.cpp -o main.s

run_assembly:
	g++ -S -O2 -fno-asynchronous-unwind-tables -fno-unwind-tables -fno-exceptions -fno-rtti main.cpp -o main.s
